import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SidebarColumn from "@/components/SidebarColumn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${styles["container"]}`}
      >
        <div className={styles["header-container"]}>
          <Header />
        </div>
        <div className={styles["main-container"]}>
          {children}
          <SidebarColumn />
        </div>
      </body>
    </html>
  );
}
